// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/codecrafters-io/interpreter-starter-go/cmd/myinterpreter/interpreter"
)

// Injectors from wire.go:

func InitializeParser() (interpreter.Parser, error) {
	v := interpreter.NewLexems()
	parenthesesScanner := interpreter.NewParenthesesScanner(v)
	parser := interpreter.NewParser(v, parenthesesScanner)
	return parser, nil
}
