// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/codecrafters-io/interpreter-starter-go/cmd/myinterpreter/interpreter"
)

// Injectors from wire.go:

func InitializeInterpreter() (interpreter.Interpreter, error) {
	errors := interpreter.NewErrors()
	lexemes := interpreter.NewLexemes(errors)
	tokenizer := interpreter.NewTokenizer(lexemes, errors)
	parser := interpreter.NewParser()
	interpreterInterpreter := interpreter.NewInterpreter(tokenizer, parser)
	return interpreterInterpreter, nil
}
